// Isolated browser acceptance; generated catalogs are read-only and saves use /tmp.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'ashen-animation-org-')),statePath=path.join(temp,'state.json');let browser,server;
(async()=>{try{
 server=spawn('python3',[path.join(__dirname,'serve_progress_tracker.py'),'--port','0','--state',statePath],{cwd:root,stdio:['ignore','pipe','pipe']});server.stderr.on('data',()=>{});
 const url=await new Promise((resolve,reject)=>{let log='';const timer=setTimeout(()=>reject(Error('server timeout')),15000);server.stdout.on('data',b=>{log+=b;const match=log.match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0]);}});});
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});const ctx=await browser.newContext({viewport:{width:1400,height:1000}}),page=await ctx.newPage(),errors=[],loads=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/\.(glb|gltf|fbx|tres|res)(?:\?|$)/i.test(r.url()))loads.push(r.url());});
 const saved=()=>page.waitForFunction(()=>document.getElementById('save-state').textContent==='Saved to project');
 await page.goto(url+'/docs/tracker/');await saved();await page.click('[data-book=art]');await page.click('[data-art-mode=models]');
 assert.equal(await page.locator('.animation-category').count(),5);assert.match(await page.locator('#summary').textContent(),/motions/);
 await page.locator('.animation-category').filter({hasText:'Combat'}).locator('.category-open').click();
 assert.ok(await page.locator('#results [data-id^="art:clip:"]').count()>0);await page.fill('#search','regular sword');
 const ids=await page.locator('#results .entry').evaluateAll(ns=>ns.map(n=>n.dataset.id));assert.ok(ids.length>1);await page.fill('#search','SWORD_regular');assert.deepEqual(await page.locator('#results .entry').evaluateAll(ns=>ns.map(n=>n.dataset.id)),ids);
 const clip=page.locator('#results .entry').first(),id=await clip.getAttribute('data-id');await clip.locator('h2 button').click();
 assert.match(await page.locator('#detail-body').textContent(),/Original clip:/);const original=await page.inputValue('#display-name');await page.fill('#display-name','My sword strike');await page.getByRole('button',{name:'Save name',exact:true}).click();await saved();assert.equal(await page.locator('#detail-title').textContent(),'My sword strike');
 await page.locator('.flags').getByText('Bug found',{exact:true}).click();await page.fill('#entry-notes','A clip-only annotation');await page.locator('input[data-classification=animation_tags][value=Healing]').check();await saved();
 const raw=JSON.parse(fs.readFileSync(statePath));assert.equal(raw.version,require('../docs/tracker/model.js').version);assert.equal(raw.items[id].display_name,'My sword strike');assert.ok(raw.items[id].animation_tags.includes('Healing'));const parent=await page.evaluate(id=>TRACKER_DATA.animation_clips.find(e=>e.id===id).parent_id,id);assert.equal(raw.items[parent],undefined);
 await page.click('#close-detail');await page.fill('#search','strike my');assert.equal(await page.locator('#results .entry').count(),1);assert.equal(await page.locator('#results .entry').getAttribute('data-id'),id);
 await page.click('[data-art-mode=ui]');assert.equal(await page.inputValue('#search'),'');assert.equal(await page.locator('#results .entry').count(),2,'One documented sequence and one video, no individual frames');assert.equal(await page.locator('#results [data-id^="art:clip:"]').count(),0);
 await page.click('[data-art-mode=models]');assert.equal(await page.inputValue('#search'),'strike my');assert.match(await page.locator('#animation-breadcrumb').textContent(),/Combat/);await page.reload();await saved();assert.equal(await page.inputValue('#search'),'strike my');
 await page.locator('#results h2 button').click();await page.getByRole('button',{name:'Reset to original name',exact:true}).click();assert.equal(await page.inputValue('#display-name'),original);await page.getByRole('button',{name:'Reset to catalog classification',exact:true}).click();await saved();const reset=JSON.parse(fs.readFileSync(statePath)).items[id];assert.equal(reset.display_name,'');assert.equal(reset.animation_tags,null);assert.equal(reset.note,'A clip-only annotation');await page.click('#close-detail');
 await page.fill('#search','');await page.click('#back-animation-categories');await page.locator('.animation-category').filter({hasText:'Combat'}).locator('.category-details').click();await page.fill('#display-name','Battle motions');await page.getByRole('button',{name:'Save name',exact:true}).click();await saved();await page.click('#close-detail');await page.fill('#search','battle');assert.equal(await page.locator('.animation-category').count(),1);assert.match(await page.locator('.animation-category h2').textContent(),/Battle motions/);
 await page.click('[data-art-mode=files]');await page.fill('#search','MainKnightReference');await page.locator('#results h2 button').click();await page.fill('#display-name','Knight appearance reference');await page.getByRole('button',{name:'Save name',exact:true}).click();await saved();await page.click('#close-detail');assert.equal(await page.locator('#results .entry').count(),1,'Original filename still finds renamed file');await page.fill('#search','appearance knight');assert.equal(await page.locator('#results .entry').count(),1);
 await page.click('[data-art-mode=models]');await page.click('#clear-filters');await page.locator('#art-filter-groups input[value="UAL 2"]').check();await page.locator('#art-filter-groups input[value="Sword attack"]').check();const matched=await page.evaluate(()=>ArtAnimations.project(TRACKER_DATA.animation_clips,TRACKER_DATA.animation_categories,{...ArtSearch.defaults(),origins:[],source_libraries:['UAL 2'],animation_tags:['Sword attack']}).matchedClipCount);assert.ok(matched>0);assert.match(await page.locator('#summary').textContent(),new RegExp(matched+' motions'));
 fs.mkdirSync(path.join(root,'.artifacts/tracker'),{recursive:true});await page.screenshot({path:path.join(root,'.artifacts/tracker/animation-organization-desktop.png')});
 await page.setViewportSize({width:390,height:850});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.click('#open-art-filters');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'open-art-filters');await page.screenshot({path:path.join(root,'.artifacts/tracker/animation-organization-mobile.png')});
 assert.deepEqual(loads,[],'Browsing/naming/filtering must load images only');assert.deepEqual(errors,[]);console.log('Animation organization: categories, unique counts, UI separation, exact clip edits, reset, source/name search, independent notes, combined filters, remembered views, mobile/keyboard and no animation downloads passed.');
 }finally{if(browser)await browser.close();if(server&&server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done;}fs.rmSync(temp,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
