'use strict';
const assert=require('node:assert/strict');
const A=require('../docs/tracker/art-search.js');
const all=()=>({...A.defaults(),origins:[]});
const sample={id:'art:sword',title:'Knight Sword 2',path:'assets/weapons/combat_pack.glb',kind:'Models',types:['Models','Animations'],collections:['Sword attacks','Knight'],origin:'Project files',role:'',clip_names:['Sword_Regular_A','Sword-Heavy-B','Shield_Block'],modified_at:'2026-09-21T12:00:00Z'};

assert.deepEqual(A.defaults(),{search:'',view:'all',types:[],collections:[],origins:['Project files'],roles:[],statuses:[],attention:[],priorities:[],animation_categories:[],animation_tags:[],source_libraries:[],rigs:[],motion_modes:[],preview_states:[],review_labels:[],art_tags:[],start_states:[],end_states:[],duplicate_states:[],naming_states:[],showDuplicateSources:false,category_id:'',overviewScroll:0,sort:'relevance',layout:'gallery',individualImages:false,showDuplicateSources:false,scroll:0,limit:60});
assert.equal(A.migrate({individualImages:true}).individualImages,true);
assert.equal(A.migrate({individualImages:'true'}).individualImages,false);
const fresh=A.defaults();fresh.origins.push('Third-party library');assert.deepEqual(A.defaults().origins,['Project files']);
assert.deepEqual(A.migrate(null),A.defaults());
let migrated=A.migrate({search:'Sword',area:'Animations',topic:'References',view:'Completed',attention:'Needs testing',priority:'High',scroll:90,limit:120});
assert.deepEqual(migrated.types,['Animations']);assert.deepEqual(migrated.origins,[]);assert.deepEqual(migrated.roles,['Reference']);assert.deepEqual(migrated.statuses,['Completed']);assert.equal(migrated.view,'all');assert.deepEqual(migrated.attention,['Needs testing']);assert.deepEqual(migrated.priorities,['High']);assert.equal(migrated.scroll,90);assert.equal(migrated.limit,120);assert.equal(migrated.search,'Sword');
for(const topic of ['Project files','Third-party library'])assert.deepEqual(A.migrate({topic}).origins,[topic]);
assert.deepEqual(A.migrate({topic:''}).origins,[],'Legacy all origins remains all origins');
assert.deepEqual(A.migrate({...A.defaults(),origins:[]}).origins,[],'New all origins survives reload');
for(const view of ['Planned','In progress','Ready for review','Completed','Deferred'])assert.deepEqual(A.migrate({view}).statuses,[view]);
assert.equal(A.migrate({view:'recent'}).view,'recent');
assert.equal(A.migrate({view:'recent'}).sort,'recent','Legacy recent view retains newest-first ordering');
assert.equal(A.migrate({view:'recent',sort:'name'}).sort,'name','Explicit new sort preference takes precedence');
migrated=A.migrate({types:[' Future type ','Future type',42,null,{},'',false],origins:[],roles:['Obsolete role'],scroll:-1,limit:'huge',sort:'unknown',layout:'unknown'});
assert.deepEqual(migrated.types,['Future type']);assert.deepEqual(migrated.roles,['Obsolete role']);assert.equal(migrated.scroll,0);assert.equal(migrated.limit,60);assert.equal(migrated.sort,'relevance');assert.equal(migrated.layout,'gallery');
assert.deepEqual(A.migrate({topic:'References',origins:['Project files'],roles:[]}).roles,[],'Explicit new fields win over legacy fields');

assert.equal(A.normalize('  ÉPÉE_Heavy—Attack  '),'epee heavy attack');
assert.equal(A.normalize('Straße'),A.normalize('STRASSE'));
const indexed=A.indexEntry(sample);assert.equal(A.indexEntry(sample),indexed,'Catalog search index is cached');
assert.equal(A.search(indexed,'REGULAR sword').matches,true,'Clip names match tokens in any order and case');
assert.equal(A.search(indexed,'sword-heavy').matches,true);assert.equal(A.search(indexed,'sword_heavy').matches,true);
assert.equal(A.search(indexed,'heavy knight').matches,true,'Tokens can cross title and clip fields');
assert.equal(A.search(indexed,'weapons rework','Needs rework').matches,true,'Tokens can cross path and user notes');
assert.equal(A.search(indexed,'animations attacks').matches,true,'Types and collections are searchable');
assert.equal(A.search(indexed,'regular absent').matches,false,'All query tokens are required');
assert.deepEqual(A.search(indexed,'regular sword').matchingClips,['Sword_Regular_A','Sword-Heavy-B']);
assert.deepEqual(A.search(indexed,'regular').matchingClips,['Sword_Regular_A']);
assert.deepEqual(A.search(indexed,'').matchingClips,[]);
assert.equal(A.search(A.indexEntry({title:'Épée'}),'epee').matches,true);
const titleHit={id:'title',title:'Regular Sword',path:'a'},clipHit={id:'clip',title:'Pack',path:'b',clip_names:['Sword_Regular_A']},noteHit={id:'note',title:'Notes',path:'c'},pathHit={id:'path',title:'A file',path:'sword_regular.glb'};
const score=e=>A.search(A.indexEntry(e),'regular sword',e===noteHit?'Regular sword':'').score;
assert.ok(score(titleHit)>score(pathHit));assert.ok(score(clipHit)>score(pathHit));assert.ok(score(clipHit)>score(noteHit));

const metadata={status:'In progress',attention:['Needs testing','Needs improvement'],priority:'High',note:'Needs polish'};
assert.equal(A.filter(sample,metadata,{...all(),types:['Animations','Lore'],collections:['Knight','Unrelated'],attention:['Bug found','Needs testing'],priorities:['High','Low']}),true,'OR applies within each group');
assert.equal(A.filter(sample,metadata,{...all(),types:['Animations'],collections:['Unrelated']}),false,'AND applies across groups');
assert.equal(A.filter(sample,metadata,{...all(),types:['Lore']}),false);
assert.equal(A.filter(sample,metadata,{...all(),roles:['Not a reference']}),true);
assert.equal(A.filter({...sample,role:'Reference'},metadata,{...all(),roles:['Not a reference']}),false);
assert.equal(A.filter(sample,{}, {...all(),statuses:['Not set'],priorities:['Normal']}),true);
assert.equal(A.filter(sample,metadata,{...all(),statuses:['Not set']}),false);
assert.equal(A.filter(sample,metadata,{...all(),statuses:['Deferred','In progress']}),true);
assert.equal(A.filter(sample,undefined,all()),true,'Absent metadata is safe');
assert.equal(A.filter({id:'missing',title:'Missing file',missing:true},undefined,{...all(),view:'missing'}),true);
assert.equal(A.filter(sample,metadata,{...all(),view:'missing'}),false);
assert.equal(A.filter(sample,metadata,{...all(),view:'attention'}),true);
assert.equal(A.filter(sample,undefined,{...all(),view:'attention'}),false);
assert.equal(A.filter({...sample,origin:'Third-party library'},metadata,A.defaults()),false);
assert.equal(A.filter({...sample,origin:'Third-party library'},metadata,all()),true);
assert.equal(A.filter(sample,metadata,{...all(),search:'polish knight'}),true);
assert.equal(A.filter(sample,undefined,{...all(),view:'recent'}),true,'File modification is recent activity');
assert.equal(A.filter({id:'old'},undefined,{...all(),view:'recent'}),false);
assert.equal(A.filter({id:'old'},undefined,{...all(),view:'recent'},{at:'2026-09-29T00:00:00Z'}),true);
assert.deepEqual(A.types({kind:'Models'}),['Models']);assert.deepEqual(A.types({kind:'Models',types:['Models','Animations']}),['Models','Animations']);assert.deepEqual(A.collections({}),[]);

const numbered=[{id:'ten',title:'Sword 10',path:'z'},{id:'two-z',title:'sword 2',path:'z'},{id:'two-a',title:'Sword 2',path:'a'}];
assert.deepEqual(A.sortEntries(numbered,{...all(),sort:'name'}).map(e=>e.id),['two-a','two-z','ten']);
assert.deepEqual(numbered.map(e=>e.id),['ten','two-z','two-a'],'Sorting does not mutate the input');
assert.deepEqual(A.sortEntries(numbered,{...all(),sort:'relevance'}).map(e=>e.id),['two-a','two-z','ten'],'Relevance without a query sorts by name');
const ranked=A.sortEntries([pathHit,noteHit,clipHit,titleHit],{...all(),search:'sword regular'},{metadata:e=>({note:e===noteHit?'Regular sword':''}),indexes:new Map([[clipHit.id,A.indexEntry(clipHit)]])});
assert.deepEqual(ranked.map(e=>e.id),['title','clip','note','path']);
const dated=[{id:'file',title:'File',modified_at:'2026-09-28T00:00:00Z'},{id:'user',title:'User',modified_at:'2026-09-20T00:00:00Z'},{id:'invalid',title:'Invalid',modified_at:'not a date'}];
const activity=new Map([['user',{at:'2026-09-29T00:00:00Z'}]]);
assert.deepEqual(A.sortEntries(dated,{...all(),sort:'recent'},{activity}).map(e=>e.id),['user','file','invalid']);
assert.deepEqual(A.sortEntries(dated,{...all(),sort:'recent'},{activity:{user:'2026-09-29T00:00:00Z'}}).map(e=>e.id),['user','file','invalid']);
assert.deepEqual(A.sortEntries(dated,{...all(),sort:'attention'},{metadata:e=>({attention:e.id==='user'?['Needs testing','Bug found']:e.id==='file'?['Needs testing']:[]})}).map(e=>e.id),['user','file','invalid']);
assert.equal(A.latestTimestamp(dated[0],{at:'2026-09-01T00:00:00Z'}),Date.parse(dated[0].modified_at));
const tagHit={id:'tag',title:'Z pose',animation_tags:['Climbing'],animation_categories:['Movement']},tagPathHit={id:'tag-path',title:'A pose',path:'climbing.glb'};
assert.equal(A.filter(tagHit,{}, {...all(),search:'climbing'}),true);
assert.deepEqual(A.sortEntries([tagPathHit,tagHit],{...all(),search:'climbing'}).map(e=>e.id),['tag','tag-path'],'Tag search and relevance use the same effective labels');
assert.equal(A.filter(tagHit,{animation_categories:[],animation_tags:[]},{...all(),search:'unclassified'}),true,'Explicit cleared categories are searchable as Unclassified');
assert.equal(A.filter(tagHit,{animation_tags:[]},{...all(),search:'climbing'}),false,'Cleared tags do not remain in the search index');
assert.deepEqual(A.sortEntries([tagPathHit,tagHit],{...all(),search:'climbing'},{metadata:e=>e===tagHit?{animation_tags:[]}: {}}).map(e=>e.id),['tag-path','tag'],'Cleared tags also stop influencing ranking');
console.log('Art search: preference migration, normalized token search, relevance, filter groups, missing metadata, clip matches, and deterministic sorting passed.');

const decisions={...A.defaults(),origins:[],review_labels:['Approved']};
const reviewEntry={id:'art:review',title:'Review fixture',types:['Images'],origin:'Project files'};
assert.equal(A.filter(reviewEntry,{review_label:'Approved'},decisions),true);
assert.equal(A.filter(reviewEntry,{review_label:'Scrap'},decisions),false);
assert.equal(A.filter(reviewEntry,{review_label:'Approved',attention:['Bug found']},{...decisions,attention:['Bug found']}),true);
assert.deepEqual(A.migrate({review_labels:['Approved','Scrap']}).review_labels,['Approved','Scrap']);

assert.doesNotThrow(()=>A.sortEntries([reviewEntry],decisions));

assert.equal(A.migrate({showDuplicateSources:true}).showDuplicateSources,true);
assert.equal(A.migrate({showDuplicateSources:'true'}).showDuplicateSources,false);
const transition={id:'transition',title:'Jump to Free Hang',original_names:['Jumping_To_Hanging'],original_paths:['old/Jumping (1).fbx'],start_state:'Standing',end_state:'Free hang',transition_steps:['Jump','Free hang'],naming_status:'verified',duplicate_status:'verified_duplicate'};
assert.equal(A.filter(transition,{}, {...all(),search:'jumping hanging'}),true);
assert.equal(A.filter(transition,{}, {...all(),search:'old jumping'}),true);
assert.equal(A.filter(transition,{}, {...all(),start_states:['Standing'],end_states:['Free hang'],naming_states:['verified']}),true);
assert.equal(A.filter(transition,{}, {...all(),start_states:['Free hang'],end_states:['Free hang']}),false);
assert.equal(A.filter(transition,{}, {...all(),duplicate_states:['candidate']}),false);

const tagged={...metadata,art_tags:['Magic','Moon Knights']};
assert(A.filter(sample,tagged,{...all(),search:'knights moon'}));
assert(A.filter(sample,tagged,{...all(),art_tags:['magic','Weapons']}));
assert(!A.filter(sample,tagged,{...all(),art_tags:['Armor']}));
assert(!A.filter(sample,tagged,{...all(),art_tags:['Magic'],types:['Images']}));
assert(!A.filter(sample,{...tagged,art_tags:[]},{...all(),search:'Moon Knights'}));
assert.deepEqual(A.migrate({art_tags:['Magic','Moon Knights']}).art_tags,['Magic','Moon Knights']);
console.log('Art tag search, case-insensitive filters, combined groups and preference persistence passed.');
