'use strict';
const assert=require('node:assert/strict');
const D=require('../docs/tracker/dev-search.js');
const f=extra=>({...D.defaults(),...extra});
const entry={id:'motion',title:'Ground Motion 2',area:'Gameplay',category:'Gameplay mechanics',topic:'Movement',subcategory:'Ground movement',dev_tags:['Movement','Ground movement'],summary:'Momentum and slope contacts',note:'Motor owns body motion',sources:['features/character/character_simulation.gd'],checklist:[]};
const meta={status:'Ready for review',attention:['Bug found','Needs testing'],priority:'High',note:'Smooth the transition',checklist:[{done:true},{done:false}],display_name:''};
assert.deepEqual(D.defaults(),{search:'',view:'all',area:'',topic:'',attention:'',priority:'',status:'',assessment:'',tag:'',sort:'relevance',scroll:0,limit:60});
assert.deepEqual(D.migrate(null),D.defaults());
assert.equal(D.migrate({view:'recent'}).sort,'recent');
assert.equal(D.migrate({view:'recent',sort:'name'}).sort,'name');
assert.deepEqual(D.migrate({area:'Gameplay',topic:'Movement',view:'Completed',attention:'Bug found',priority:'High',search:'slope',scroll:900,limit:120}),f({area:'Gameplay',topic:'Movement',view:'Completed',attention:'Bug found',priority:'High',search:'slope',scroll:900,limit:120}));
assert.equal(D.migrate({limit:-1,scroll:'bad',sort:'unknown'}).limit,60);
assert.deepEqual(D.tags({...entry,dev_tags:['Movement','Movement','']}),['Movement']);
assert.equal(D.indexEntry(entry),D.indexEntry(entry),'Immutable catalog indexes are cached');
for(const search of ['contacts MOMENTUM','slope_ground','ground—motion','motor transition','simulation character','Gameplay slope'])assert.equal(D.filter(entry,meta,f({search})),true,search);
assert.equal(D.filter(entry,meta,f({search:'slope absent'})),false,'Every token is required');
assert.equal(D.filter(entry,{...meta,display_name:'Slope master'},f({search:'master slope'})),true);
assert.equal(D.filter(entry,{...meta,display_name:'Slope master'},f({search:'ground motion'})),true,'Original name remains searchable');
assert.equal(D.filter(entry,meta,f({area:'Gameplay',topic:'Movement',tag:'Ground movement',status:'Ready for review',attention:'Bug found',priority:'High'})),true);
for(const wrong of [{area:'Systems'},{topic:'Combat'},{tag:'Combat'},{status:'Completed'},{attention:'Blocked'},{priority:'Low'}])assert.equal(D.filter(entry,meta,f(wrong)),false);
for(const status of ['Planned','In progress','Ready for review','Completed','Deferred']){
 assert.equal(D.filter(entry,{...meta,status},f({status})),true);
 assert.equal(D.filter(entry,{...meta,status},f({view:status})),true,'Legacy status view remains supported');
}
assert.equal(D.filter(entry,meta,f({view:'attention'})),true);
assert.equal(D.filter(entry,{...meta,attention:[]},f({view:'attention'})),false);
assert.equal(D.filter(entry,meta,f({view:'missing'})),false);
assert.equal(D.filter({...entry,missing:true},meta,f({view:'missing'})),true);
assert.equal(D.filter(entry,meta,f({view:'recent'})),false);
assert.equal(D.filter(entry,meta,f({view:'recent'}),{at:'2026-09-29T10:00:00Z'}),true);
assert.equal(D.filter({...entry,modified_at:'2026-09-29T10:00:00Z'},meta,f({view:'recent'})),true);
for(const assessment of ['assessed','incomplete_checks'])assert.equal(D.filter(entry,meta,f({assessment})),true);
for(const assessment of ['unassessed','complete_checks'])assert.equal(D.filter(entry,meta,f({assessment})),false);
const empty={...meta,checklist:[]},complete={...meta,checklist:[{done:true}]};
assert.equal(D.filter(entry,empty,f({view:'unassessed'})),true);
assert.equal(D.filter(entry,empty,f({assessment:'complete_checks'})),false,'Empty checklists are never complete');
assert.equal(D.filter(entry,complete,f({assessment:'complete_checks'})),true);
assert.equal(D.filter(entry,complete,f({assessment:'incomplete_checks'})),false);
assert.equal(D.filter(entry,{...complete,status:'Deferred',attention:['Bug found']},f({assessment:'complete_checks'})),true,'Deferred status and quality flags do not change checklist math');
const rows=[{id:'path',title:'A',sources:['motion.gd']},{id:'description',title:'B',summary:'motion'},{id:'name',title:'Motion'},{id:'custom',title:'C'}];
const metadata=e=>e.id==='custom'?{display_name:'Motion'}:{};
assert.deepEqual(D.sort(rows,f({search:'motion'}),{metadata}).map(e=>e.id),['custom','name','description','path'],'Names rank ahead of descriptions and paths');
assert.deepEqual(rows.map(e=>e.id),['path','description','name','custom'],'Sorting is non-mutating');
const ordered=[{id:'unassessed',title:'A'},{id:'low',title:'B'},{id:'high',title:'C'}];
const tracking={unassessed:{checklist:[],priority:'Normal'},low:{checklist:[{done:false}],priority:'Low',attention:['Bug found']},high:{checklist:[{done:true}],priority:'High',attention:['Bug found','Needs testing']}};
const options={metadata:e=>tracking[e.id]};
assert.deepEqual(D.sort(ordered,f({sort:'progress'}),options).map(e=>e.id),['high','low','unassessed']);
assert.deepEqual(D.sort(ordered,f({sort:'priority'}),options).map(e=>e.id),['high','unassessed','low']);
assert.deepEqual(D.sort(ordered,f({sort:'attention'}),options).map(e=>e.id),['high','low','unassessed']);
for(const activity of [new Map([['high','2026-09-29'],['low','2026-09-28']]),{high:{at:'2026-09-29'},low:'2026-09-28'}])assert.deepEqual(D.sort(ordered,f({sort:'recent'}),{...options,activity}).map(e=>e.id),['high','low','unassessed']);
assert.deepEqual(D.sort([{id:'2',title:'Feature 10'},{id:'1',title:'Feature 2'}],f({sort:'name'})).map(e=>e.id),['1','2']);
assert.deepEqual(D.sort([{id:'z',title:'Same'},{id:'a',title:'Same'}],f({sort:'name'})).map(e=>e.id),['a','z'],'Ties are deterministic');
console.log('Dev search: preference migration, source-backed tags, unordered search, independent status/quality/checklist filters and six deterministic sorts passed.');
