'use strict';
const assert=require('node:assert/strict');
const A=require('../docs/tracker/art-search.js');
const B=require('../docs/tracker/animation-browser.js');
const filters=()=>({...A.defaults(),origins:[]});
const clip=(id,categories,extra={})=>({id:'art:clip:'+id,parent_id:'art:source',title:id,types:['Animations'],animation_categories:categories,animation_tags:[],preview:{kind:'model',status:'ready'},...extra});
const category=title=>({id:'art:category:'+title.toLowerCase(),title,category_label:title,members:[],animation_category:true});
const categories=['Combat','Movement','Unclassified'].map(category);
const entries=[clip('attack',['Combat']),clip('leap',['Combat','Movement'],{animation_tags:['Jumping'],source_library:'UAL 2'}),clip('walk',['Movement'],{source_library:'UAL 1'})];
let result=B.project(entries,categories,filters());
assert.equal(result.matchedClipCount,3,'A clip assigned to two chapters counts only once');
assert.deepEqual(result.entries.map(e=>e.matching_count),[2,2]);
const edited=e=>e.title==='attack'?{animation_categories:[],animation_tags:[]}:{};
result=B.project(entries,categories,filters(),{metadata:edited});
assert.equal(result.entries.find(e=>e.category_label==='Unclassified').matching_count,1,'Explicit cleared categories move the clip to Unclassified');
assert.deepEqual(B.labels(entries[0],{animation_categories:null}).categories,['Combat'],'Null resets to the generated categories');
result=B.project(entries,categories,{...filters(),animation_tags:['Jumping'],source_libraries:['UAL 1']});
assert.equal(result.entries.length,0,'Tags and libraries must match the same clip');
result=B.project(entries,categories,{...filters(),animation_tags:['Jumping','Absent'],source_libraries:['UAL 2']});
assert.equal(result.matchedClipCount,1,'OR within a facet and AND between facets');
const renamed=e=>e.id===categories[0].id?{display_name:'Battle motions'}:{};
result=B.project(entries,categories,{...filters(),search:'battle'}, {metadata:renamed});
assert.equal(result.entries.length,1);assert.equal(result.matchedClipCount,2,'A custom category name exposes its members');
result=B.project(entries,categories,{...filters(),category_id:categories[0].id,search:'battle',source_libraries:['UAL 1']},{metadata:renamed});
assert.equal(result.entries.length,0,'Category-name search does not bypass other facets');
result=B.project([clip('recent',['Movement'])],categories,{...filters(),view:'recent'},{activity:{'art:clip:recent':{at:'2026-09-29T00:00:00Z'}}});
assert.equal(result.matchedClipCount,1,'History objects and Maps both work');
const parent={id:'art:source',preview:{kind:'model',status:'unavailable'}};
assert.equal(B.modelEntries([parent,...entries]).length,3,'Source files do not duplicate known clip records');
assert.equal(B.modelEntries([{id:'art:unknown',preview:{kind:'model',status:'unavailable'}}])[0].unresolved_animation,true);

const frames=Array.from({length:600},(_,i)=>({id:'art:frame:'+i,collections:['UI'],preview:{kind:'sequence',status:'stale',sequence:{id:'ui-demo',start_frame:i}}}));
const pack={id:'art:pack:ui',collections:['UI'],members:frames.map(e=>e.id),preview_member:frames[0].id};
const atlas={id:'art:atlas',collections:['UI'],preview:{kind:'sequence',status:'stale',sequence:{id:'ui-demo'}}};
const video={id:'art:video',collections:['UI'],preview:{kind:'video',status:'ready'}};
const missing={...frames[0],missing:true,preview:{kind:'model',status:'unavailable',reason:'The original asset is missing'}};
const ui=B.uiEntries([missing,...frames.slice(1),atlas,video,pack]);
assert.deepEqual(ui.map(e=>e.id),[pack.id,video.id],'A missing first frame produces one sequence pack, never 599 frame cards');
assert.equal(ui[0].preview.status,'unavailable');assert.equal(ui[0].preview.sequence.id,'ui-demo');
assert.equal(B.uiEntries(frames).length,1,'A sequence without a pack still groups by documented sequence identity');
assert.equal(B.uiEntries([{...pack,preview:{kind:'sequence',status:'ready',sequence:{id:'ui-demo'}}},...frames,atlas]).length,1);
assert.equal(B.uiEntries([{...pack,members:['absent']}])[0].preview.status,'unavailable','An entirely missing documented sequence remains visible');
assert.equal(B.uiEntries([{id:'art:still',collections:['UI'],preview:{kind:'model',status:'unavailable'}}]).length,0,'Ordinary UI images are not invented sequences');
console.log('Animation browser: category counts, overrides, combined facets, custom names, activity maps, unresolved files and missing/stale sequence grouping passed.');

const duplicate=clip('copy',['Movement'],{duplicate_group:'pair',duplicate_status:'verified_duplicate',duplicate_keeper_id:'art:clip:keeper',source_library:'Copy',start_state:'Hang'});
const keeper=clip('keeper',['Movement'],{...duplicate,id:'art:clip:keeper',source_library:'Original',start_state:'Standing'});
const candidate=clip('candidate',['Movement'],{...duplicate,id:'art:clip:candidate',duplicate_status:'candidate'});
assert.deepEqual(B.groupDuplicates([duplicate,keeper]).map(e=>e.id),[keeper.id]);
assert.equal(B.groupDuplicates([duplicate,keeper,candidate]).length,2,'Unverified candidates never collapse');
assert.equal(B.groupDuplicates([duplicate,keeper],undefined,true).length,2);
result=B.project([duplicate,keeper],categories,filters());assert.equal(result.matchedClipCount,1);assert.equal(result.sourceClipCount,2);
result=B.duplicateEntries([duplicate,keeper],{...filters(),source_libraries:['Copy']});assert.equal(result.entries[0].id,duplicate.id,'Only a matching source can represent a group');
result=B.duplicateEntries([duplicate,keeper],{...filters(),source_libraries:['Copy'],start_states:['Standing']});assert.equal(result.entries.length,0,'Sources cannot combine different facet matches');
assert.equal(B.duplicateEntries([duplicate,keeper],{...filters(),showDuplicateSources:true}).entries.length,2);
